### ISSUE TITLE
String comparisons in MainActivity.java (and possibly elsewhere)

### ISSUE THREAD

**Issue by matthewcmckenna** [googlesamples/gcm-playground#19]
The string comparisons in [MyActivity.java](https://github.com/googlesamples/gcm-playground/blob/master/android/app/src/main/java/com/google/samples/apps/gcmplayground/MyActivity.java) are done using ```!=``` rather than comparing the objects. I am under the belief that this can lead to unstable behavior. Since these comparisons are against the empty string comparisons can be easily switched to ```.length()``` or ```.equals()```. Both of which should be more consistent.

**Comment by silvolu** [comment]
@matthewcmckenna thanks for your feedback! If you have time to submit a pull request, that would be great, otherwise I'll fix it as soon as I can.

**Comment by silvolu** [comment]
Fixed by #20
