### ISSUE TITLE
Server startup failure (type issues)

### ISSUE THREAD

**Issue by KenGorab** [googlesamples/gcm-playground#26]
When I run `./start.sh` I get the following output for the server:

`server_1 | ./server.go:198: cannot use 10 (type int) as type string in field value`

I tried changing the code from

    m := gcm.XmppMessage{
		To:       token,
		Priority: 10,
		Data:     d,
    }

to

    m := gcm.XmppMessage{
		To:       token,
		Priority: "10",
		Data:     d,
    }

to satisfy the type-checker. The server starts up just fine, but when trying to register the Android app as a client I get this error (formatted for readability)

    server_1 |
        <message><data:gcm xmlns:data="google:mobile:data">
        {
            "message_type": "nack",
            "from": "...",
            "message_id": "...",
            "error": "INVALID_JSON",
            "error_description": "InvalidJson: JSON_TYPE_ERROR : Field \"priority\" must be a JSON an integer priority or a specific string (high or normal): 10"
        }
        </data:gcm></message>

I'm not sure what the solution is here, anybody have any help/suggestions?

**Comment by silvolu** [comment]
You might need to run `docker-compose` before running `start.sh`, as the latter contains `docker-up` that doesn't seem to rebuild the images.
