### ISSUE TITLE
How to disable the Google cloud Messaging (GCM) using the API call from app server?

### ISSUE THREAD

**Issue by shmdhussain** [googlesamples/gcm-playground#32]
How to disable the Google cloud Messaging (GCM) using the API call from my server, without going to the https://console.developers.google.com/apis/api/googlecloudmessaging/overview

Thanks in advance for any help.
![screen shot 2016-03-08 at 15 17 45](https://cloud.githubusercontent.com/assets/4039657/13628551/7e890b42-e5ec-11e5-854a-4f4dfaf6c9d1.png)

**Comment by karan** [comment]
I'm pretty sure that's the only way.

**Comment by keyboardsurfer** [comment]
This question is not related to the sample. Please use the recommended [support forum](https://github.com/googlesamples/gcm-playground#support).
